---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment-v1
  namespace: api
  labels:
    app: demo-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v1
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
      - name: demo-app
        image: ahnsv/golang-server:latest
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /v1/api/healthcheckz
              port: 1323
            initialDelaySeconds: 3
            periodSeconds: 5
        readinessProbe:
            httpGet:
              path: /v1/api/healthcheckz
              port: 1323
            initialDelaySeconds: 2
            periodSeconds: 2
        resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: demo-app-service
  labels:
    app: demo-app
    service: demo-app-service
spec:
  ports:
    - port: 80
      targetPort: 1323
      name: http-web
  type: ClusterIP
  selector:
    app: demo-app
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-app-gateway
  namespace: api
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"